version: "3.7"
services:
  app:
    build:
      args:
        user: Ramy
        uid: 1000
      context: ./deploy
      dockerfile: Dockerfile
    image: parent
    container_name: parent-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - parent

  db:
    image: mariadb
    container_name: parent-db
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    restart: unless-stopped
    ports:
      - 56978
      - 33062:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./deploy/mysql:/docker-entrypoint-initdb.d
    networks:
      - parent

  nginx:
    image: nginx:stable-alpine
    container_name: parent-nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./:/var/www
      - ./deploy/nginx:/etc/nginx/conf.d/
    networks:
      - parent

networks:
  parent:
    driver: bridge
